app/main/routes.py
from flask import flash, redirect, session, url_for, render_template, request, Blueprint, jsonify
from app.users.routes import current_user

from app import db
from app.helpers import login_required
from app.models import Company, Employee, PayItem, EmployeePayItem, User, MonthlyPayItem, PayRun, MonthlyEmployee, MonthResult
from app.calculations.forms import (AddCompany, AddEmployee, CalculateInitial, EditEmployee, 
                        EditCompany, PayItems, AddEmployeePayItems, AuthorizationForm, PayRunForm)
from app.calculations.funktioner import Expat


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
@login_required
def home():

    user = User.query.filter_by(id=current_user.get_id()).first()
    
    return render_template("company/home.html",company = user.access)

@main.route("/home/<int:company_id>")
def chosen_company(company_id):

    company = Company.query.get_or_404(company_id)
    session['current_company'] = company.company_name

    return redirect(url_for('main.employee'))

@main.route("/employee", methods=["GET", "POST"])
@login_required
def employee():

    page = request.args.get('page', 1, type=int)
    form = AddEmployee()

    try:
        get_company = Company.query.filter_by(company_name = session['current_company']).first()
        all_employees = Employee.query.filter_by(company_id = get_company.id).paginate(page = page, per_page = 5)
    except:
        flash('You need to pick a company first!', 'danger')
        return redirect(url_for('main.home'))

    return render_template("employees/employee_grid.html",employees = all_employees, company = get_company, form = form)

@main.route("/employeeForm", methods=["GET", "POST"])
@login_required
def employeeForm():

    form = AddEmployee()
    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        emp_to_add = Employee(first_name = form.first_name.data, last_name = form.last_name.data, person_nummer = form.person_nummer.data,
                             skattetabell = form.skattetabell.data, expat_type = form.expat_type.data, assign_start = form.assign_start.data,
                             assign_end = form.assign_end.data, expert = form.expert.data, sink = form.sink.data, six_month_rule = form.six_month_rule.data,
                             social_security = form.social_security.data, company_id = current_company) 

        db.session.add(emp_to_add)
        db.session.commit()

        flash('the employee has been added! You can now start calculating', 'success')
        return jsonify(status="ok")
    return render_template("modalForms/addEmployeeForm.html", form = form)

@main.route("/editEmployeeForm/<int:employee_id>", methods=["GET", "POST"])
@login_required
def editEmployeeForm(employee_id):
    employee = Employee.query.get_or_404(employee_id)
    session["current_employee"] = employee_id
    emp_pay_items = employee.pay_items

    form = EditEmployee(obj=employee)
    pay_form = AddEmployeePayItems()

    current_company = Company.query.filter_by(company_name = session['current_company']).first()
    company_pay_items = current_company.pay_items
    

    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        try:
            employee = Employee.query.get_or_404(employee_id)
        except:
            flash('Employee not found!', 'danger')
            return redirect(url_for('main.home'))

        form.populate_obj(employee)

        db.session.commit()

        flash('the employee has been updated! You can now start calculating', 'success')
        return jsonify(status="ok")

    return render_template("modalForms/editEmployee.html", form = form, employee = employee, company_pay_items = company_pay_items, emp_pay_items = emp_pay_items, pay_form = pay_form)



@main.route("/employee/<int:employee_id>")
def chosen_employee(employee_id):
    employee = Employee.query.get_or_404(employee_id)

    get_employee = Employee.query.filter_by(id = employee.id).first()
    session['employee'] = get_employee.id

    return redirect(url_for('main.calculate'))

@main.route("/add_company", methods=["GET", "POST"])
@login_required
def add_company():

    form = AddCompany()
    session["current_company"] = ""

    if form.validate_on_submit():
        comp_to_add = Company(company_name = form.company_name.data, org_number = form.org_number.data,
                             permanent_establishment = form.permanent_establishment.data) 

        db.session.add(comp_to_add)
        db.session.commit()

        added_company = Company.query.filter_by(company_name = form.company_name.data).first()
        user = User.query.filter_by(id=current_user.get_id()).first()

        user.access.append(added_company)
        db.session.commit()

        session['current_company'] = form.company_name.data

        flash('the company has been created! You can now add employees', 'success')
        return redirect(url_for('main.settings'))

    return render_template("company/company_settings.html", form=form, current_company = False, title='Company', pay_items = False)



@main.route("/settings", methods=["GET", "POST"])
@login_required
def settings():

    try:
        current_company = Company.query.filter_by(company_name = session['current_company']).first()
        edit_form = EditCompany(obj=current_company)
    except:
        edit_form = EditCompany()

    try:
        page = request.args.get('page', 1, type=int)
        pay_items = PayItem.query.filter_by(company_id = current_company.id).paginate(page = page, per_page = 5)
    except:
        pay_items = False

    authorization_form = AuthorizationForm()
    authorized_users = current_company.users

    if edit_form.validate_on_submit():
        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first()
        except:
            flash('Some error with chosen company', 'danger')

        edit_form.populate_obj(current_company)
        db.session.commit()
        session['current_company'] = edit_form.company_name.data

        flash('the company has been edited!', 'success')
        return redirect(url_for('main.settings'))

    return render_template("company/company_settings.html", current_company = current_company, form = edit_form,
             pay_items = pay_items, authorization_form = authorization_form, authorized_users = authorized_users)


@main.route("/company_start", methods=["GET", "POST"])
@login_required
def company_start():

    form = PayRunForm()

    try:
        current_company = Company.query.filter_by(company_name = session['current_company']).first()
        pay_runs = current_company.payroll_runs
    except:
        flash('You need to pick a company first!', 'danger')
        return redirect(url_for('main.home'))

    return render_template("company/company_start.html", current_company = current_company, pay_runs = pay_runs, form = form)


@main.route("/pay_item", methods=["GET", "POST"])
@login_required
def pay_item():

    form = PayItems()
    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        pay_item = PayItem(pay_item = form.pay_item.data, tax_setting = form.tax_setting.data, cash_type = form.cash_type.data, company_id = current_company) 
        db.session.add(pay_item)
        db.session.commit()

        flash('the pay item has been added! You can now start calculating', 'success')
        return jsonify(status="ok")
    return render_template("modalForms/payItemForm.html", form = form)


@main.route("/pay_item/<int:pay_id>/delete", methods=["GET", "POST"])
@login_required
def delete_pay_item(pay_id):

    if request.method == 'POST':
        chosen_item = PayItem.query.get_or_404(pay_id)
        db.session.delete(chosen_item)
        db.session.commit()

        return jsonify(status="ok")
    else:
        return render_template("modalForms/deletePayItem.html",pay_id = pay_id)

@main.route("/emp_pay_item/<int:employee_id>", methods=["GET", "POST"])
@login_required
def emp_pay_item(employee_id):

    employee = Employee.query.get_or_404(employee_id)
    form = EditEmployee(obj=employee)

    current_company = Company.query.filter_by(company_name = session['current_company']).first()
    company_pay_items = current_company.pay_items
    emp_pay_items = employee.pay_items
    pay_form = AddEmployeePayItems()

    if pay_form.validate_on_submit():

        chosen_item = request.form.get('payitemss')
        amount = request.form.get('amount')
        currency = request.form.get('currency')


        to_add = EmployeePayItem(pay_item_id=chosen_item, amount = amount, currency = currency, employee_id = employee_id)
        db.session.add(to_add)
        db.session.commit()

        item_to_return = EmployeePayItem.query.filter_by(pay_item_id = chosen_item, amount = amount).first()
        company_pay_item = PayItem.query.filter_by(id=item_to_return.pay_item_id).first()
        return jsonify(status="ok", pay_item_id=item_to_return.id, pay_item = company_pay_item.pay_item, tax_setting = company_pay_item.tax_setting, cash_type = company_pay_item.cash_type, amount = amount, currency = currency, employee_id = employee_id)

app/templates/employees/add_employee.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}
<div class="titlebar-container">
    <div class="titlebar">
        <h1 class="title">You are adding employees to: {{ current_company.company_name }}</h1>
    </div>
</div>

    <div class="form-group">
        <form action="/add_employee" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Add Employee! </legend>
                <div class="form-group">
                    {{ form.first_name.label(class="form-control-label") }}
                    {% if form.first_name.errors %}
                        {{ form.first_name(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.first_name.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.first_name(class="form-control form-control-lg") }}
                    {% endif %}                      
                </div>
                <div class="form-group">
                    {{ form.last_name.label(class="form-control-label") }}
                    {% if form.last_name.errors %}
                        {{ form.last_name(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.last_name.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.last_name(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-group">
                    {{ form.person_nummer.label(class="form-control-label") }}
                    {% if form.person_nummer.errors %}
                        {{ form.person_nummer(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.person_nummer.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.person_nummer(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-group">
                    {{ form.skattetabell.label(class="form-control-label") }}
                    {% if form.skattetabell.errors %}
                        {{ form.skattetabell(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.skattetabell.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.skattetabell(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-group">
                    {{ form.expat_type.label(class="form-control-label") }}
                    {% if form.expat_type.errors %}
                        {{ form.expat_type(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.expat_type.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.expat_type(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-group">
                    {{ form.assign_start.label(class="form-control-label") }}
                    {% if form.assign_start.errors %}
                        {{ form.assign_start(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.assign_start.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.assign_start(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-group">
                    {{ form.assign_end.label(class="form-control-label") }}
                    {% if form.assign_end.errors %}
                        {{ form.assign_end(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.assign_end.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.assign_end(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-check">
                    {{ form.expert(class="form-check-input") }}
                    {{ form.expert.label(class="form-check-label") }}
                </div>
                <div class="form-check">
                    {{ form.sink(class="form-check-input") }}
                    {{ form.sink.label(class="form-check-label") }}
                </div>
                <div class="form-check">
                    {{ form.six_month_rule(class="form-check-input") }}
                    {{ form.six_month_rule.label(class="form-check-label") }}
                </div>
                <div class="form-group">
                    {{ form.social_security.label(class="form-control-label") }}
                    {% if form.social_security.errors %}
                        {{ form.social_security(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.social_security.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.social_security(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Want to choose a company? <a class="ml-2" href="{{ url_for('main.home') }}">Pick now</a>
        </small>
    </div>


{% endblock %}

app/templates/employees/employee_grid.html
{% extends "layout_no_container.html" %}

{% block title %}
    Log In
{% endblock %}

{% block main %}
<ul class="nav justify-content-center" id="second_navbar">
    {% if company %}
        <h4 class="nav_heading"><a class="nav-heading" id="nav-start" href="{{ url_for('main.company_start') }}">Start</a></h4>
        <h4 class="nav_heading"><a class="nav-heading" id="nav-settings" href="{{ url_for('main.settings') }}">Settings</a></h4>
        <h4 class="nav_heading"><a class="nav-heading active-nav" id="nav-employees" href="{{ url_for('main.employee') }}">Employees</a></h4>
    {% else %}
        <h4 class="nav_heading disabled-nav"><a>Start</a></h4>
        <h4 class="nav_heading active-nav"><a>Settings</a></h4>
        <h4 class="nav_heading disabled-nav"><a>Employees</a></h4>
    {% endif %}
</ul>
<div class="container p-5">
        <div class="titlebar-container">
            <div class="titlebar">
                <h1 class="title">{{ company.company_name }}</h1>
            </div>
        </div>
        <div class="left-align-button">
            <button type="button" class="btn btn-primary" onclick="editEmployee('{{ url_for('main.employeeForm') }}')">Add Employee</button>
        </div>
        <table class="table table-striped table-dark">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First Name</th>
                    <th scope="col">Last Name</th>
                    <th scope="col">Person Nummer</th>
                </tr>
            </thead>
            <tbody>
                {% for item in employees.items %}
                    <tr> 
                        <th scope="row">{{ item.id }}</th>
                        <td>{{ item.first_name }}</td>
                        <td>{{ item.last_name }}</td>
                        <td>{{ item.person_nummer }}</td>
                        <td><button type="button" class="btn btn-primary" onclick="editEmployee('{{ url_for('main.editEmployeeForm', employee_id=item.id) }}')">Edit Employee</button></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        {% for page_num in employees.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
            {% if employees.page == page_num %}
                <a class="btn btn-info mb-4" href= "{{ url_for('main.employee', page=page_num) }}">{{ page_num }}</a>
            {% else %}
                <a class="btn btn-outline-info mb-4" href= "{{ url_for('main.employee', page=page_num) }}">{{ page_num }}</a>
            {% endif %}     
        {% else %}

        {% endif %}
        {% endfor %}
</div>
    

<div class="modal fade bd-example-modal-xl" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" id="myModal">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">

            </div>
        </div>
</div>


<script>


function editEmployee(url){
      $.get(url, function(data) {
        $('#myModal .modal-content').html(data);
        $('#myModal').modal();
      });
    }
      

</script>

{% endblock %}