app/main/routes.py
from flask import flash, redirect, session, url_for, render_template, request, Blueprint, jsonify
from app.users.routes import current_user

from app import db
from app.helpers import login_required
from app.models import Company, Employee, PayItem, EmployeePayItem, User, MonthlyPayItem, PayRun, MonthlyEmployee, MonthResult
from app.calculations.forms import (AddCompany, AddEmployee, CalculateInitial, EditEmployee, 
                        EditCompany, PayItems, AddEmployeePayItems, AuthorizationForm, PayRunForm)
from app.calculations.funktioner import Expat


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
@login_required
def home():

    user = User.query.filter_by(id=current_user.get_id()).first()
    
    return render_template("company/home.html",company = user.access)

@main.route("/home/<int:company_id>")
def chosen_company(company_id):

    company = Company.query.get_or_404(company_id)
    session['current_company'] = company.company_name

    return redirect(url_for('main.employee'))

@main.route("/employee", methods=["GET", "POST"])
@login_required
def employee():

    page = request.args.get('page', 1, type=int)
    form = AddEmployee()

    try:
        get_company = Company.query.filter_by(company_name = session['current_company']).first()
        all_employees = Employee.query.filter_by(company_id = get_company.id).paginate(page = page, per_page = 5)
    except:
        flash('You need to pick a company first!', 'danger')
        return redirect(url_for('main.home'))

    return render_template("employees/employee_grid.html",employees = all_employees, company = get_company, form = form)

@main.route("/employeeForm", methods=["GET", "POST"])
@login_required
def employeeForm():

    form = AddEmployee()
    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        emp_to_add = Employee(first_name = form.first_name.data, last_name = form.last_name.data, person_nummer = form.person_nummer.data,
                             skattetabell = form.skattetabell.data, expat_type = form.expat_type.data, assign_start = form.assign_start.data,
                             assign_end = form.assign_end.data, expert = form.expert.data, sink = form.sink.data, six_month_rule = form.six_month_rule.data,
                             social_security = form.social_security.data, company_id = current_company) 

        db.session.add(emp_to_add)
        db.session.commit()

        flash('the employee has been added! You can now start calculating', 'success')
        return jsonify(status="ok")
    return render_template("modalForms/addEmployeeForm.html", form = form)

@main.route("/editEmployeeForm/<int:employee_id>", methods=["GET", "POST"])
@login_required
def editEmployeeForm(employee_id):
    employee = Employee.query.get_or_404(employee_id)
    session["current_employee"] = employee_id
    emp_pay_items = employee.pay_items

    form = EditEmployee(obj=employee)
    pay_form = AddEmployeePayItems()

    current_company = Company.query.filter_by(company_name = session['current_company']).first()
    company_pay_items = current_company.pay_items
    

    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        try:
            employee = Employee.query.get_or_404(employee_id)
        except:
            flash('Employee not found!', 'danger')
            return redirect(url_for('main.home'))

        form.populate_obj(employee)

        db.session.commit()

        flash('the employee has been updated! You can now start calculating', 'success')
        return jsonify(status="ok")

    return render_template("modalForms/editEmployee.html", form = form, employee = employee, company_pay_items = company_pay_items, emp_pay_items = emp_pay_items, pay_form = pay_form)



@main.route("/employee/<int:employee_id>")
def chosen_employee(employee_id):
    employee = Employee.query.get_or_404(employee_id)

    get_employee = Employee.query.filter_by(id = employee.id).first()
    session['employee'] = get_employee.id

    return redirect(url_for('main.calculate'))

@main.route("/add_company", methods=["GET", "POST"])
@login_required
def add_company():

    form = AddCompany()
    session["current_company"] = ""

    if form.validate_on_submit():
        comp_to_add = Company(company_name = form.company_name.data, org_number = form.org_number.data,
                             permanent_establishment = form.permanent_establishment.data) 

        db.session.add(comp_to_add)
        db.session.commit()

        added_company = Company.query.filter_by(company_name = form.company_name.data).first()
        user = User.query.filter_by(id=current_user.get_id()).first()

        user.access.append(added_company)
        db.session.commit()

        session['current_company'] = form.company_name.data

        flash('the company has been created! You can now add employees', 'success')
        return redirect(url_for('main.settings'))

    return render_template("company/company_settings.html", form=form, current_company = False, title='Company', pay_items = False)



@main.route("/settings", methods=["GET", "POST"])
@login_required
def settings():

    try:
        current_company = Company.query.filter_by(company_name = session['current_company']).first()
        edit_form = EditCompany(obj=current_company)
    except:
        edit_form = EditCompany()

    try:
        page = request.args.get('page', 1, type=int)
        pay_items = PayItem.query.filter_by(company_id = current_company.id).paginate(page = page, per_page = 5)
    except:
        pay_items = False

    authorization_form = AuthorizationForm()
    authorized_users = current_company.users

    if edit_form.validate_on_submit():
        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first()
        except:
            flash('Some error with chosen company', 'danger')

        edit_form.populate_obj(current_company)
        db.session.commit()
        session['current_company'] = edit_form.company_name.data

        flash('the company has been edited!', 'success')
        return redirect(url_for('main.settings'))

    return render_template("company/company_settings.html", current_company = current_company, form = edit_form,
             pay_items = pay_items, authorization_form = authorization_form, authorized_users = authorized_users)


@main.route("/company_start", methods=["GET", "POST"])
@login_required
def company_start():

    form = PayRunForm()

    try:
        current_company = Company.query.filter_by(company_name = session['current_company']).first()
        pay_runs = current_company.payroll_runs
    except:
        flash('You need to pick a company first!', 'danger')
        return redirect(url_for('main.home'))

    return render_template("company/company_start.html", current_company = current_company, pay_runs = pay_runs, form = form)


@main.route("/pay_item", methods=["GET", "POST"])
@login_required
def pay_item():

    form = PayItems()
    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        pay_item = PayItem(pay_item = form.pay_item.data, tax_setting = form.tax_setting.data, cash_type = form.cash_type.data, company_id = current_company) 
        db.session.add(pay_item)
        db.session.commit()

        flash('the pay item has been added! You can now start calculating', 'success')
        return jsonify(status="ok")
    return render_template("modalForms/payItemForm.html", form = form)


@main.route("/pay_item/<int:pay_id>/delete", methods=["GET", "POST"])
@login_required
def delete_pay_item(pay_id):

    if request.method == 'POST':
        chosen_item = PayItem.query.get_or_404(pay_id)
        db.session.delete(chosen_item)
        db.session.commit()

        return jsonify(status="ok")
    else:
        return render_template("modalForms/deletePayItem.html",pay_id = pay_id)

@main.route("/emp_pay_item/<int:employee_id>", methods=["GET", "POST"])
@login_required
def emp_pay_item(employee_id):

    employee = Employee.query.get_or_404(employee_id)
    form = EditEmployee(obj=employee)

    current_company = Company.query.filter_by(company_name = session['current_company']).first()
    company_pay_items = current_company.pay_items
    emp_pay_items = employee.pay_items
    pay_form = AddEmployeePayItems()

    if pay_form.validate_on_submit():

        chosen_item = request.form.get('payitemss')
        amount = request.form.get('amount')
        currency = request.form.get('currency')


        to_add = EmployeePayItem(pay_item_id=chosen_item, amount = amount, currency = currency, employee_id = employee_id)
        db.session.add(to_add)
        db.session.commit()

        item_to_return = EmployeePayItem.query.filter_by(pay_item_id = chosen_item, amount = amount).first()
        company_pay_item = PayItem.query.filter_by(id=item_to_return.pay_item_id).first()
        return jsonify(status="ok", pay_item_id=item_to_return.id, pay_item = company_pay_item.pay_item, tax_setting = company_pay_item.tax_setting, cash_type = company_pay_item.cash_type, amount = amount, currency = currency, employee_id = employee_id)

app/templates/modalForms/addEmployeeForm.html
<div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Add Employee!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
            
            <div class="form-group">
                <form action="{{ url_for('main.employeeForm') }}" method="post" id="editForm">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <div class="form-group">
                            {{ form.first_name.label(class="form-control-label") }}
                            {% if form.first_name.errors %}
                                {{ form.first_name(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.first_name.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.first_name(class="form-control form-control-lg") }}
                            {% endif %}                      
                        </div>
                        <div class="form-group">
                            {{ form.last_name.label(class="form-control-label") }}
                            {% if form.last_name.errors %}
                                {{ form.last_name(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.last_name.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.last_name(class="form-control form-control-lg") }}
                            {% endif %}  
                        </div>
                        <div class="form-group">
                            {{ form.person_nummer.label(class="form-control-label") }}
                            {% if form.person_nummer.errors %}
                                {{ form.person_nummer(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.person_nummer.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.person_nummer(class="form-control form-control-lg", placeholder="YYMMDD-XXXX") }}
                            {% endif %}  
                        </div>
                        <div class="form-group">
                            {{ form.skattetabell.label(class="form-control-label") }}
                            {% if form.skattetabell.errors %}
                                {{ form.skattetabell(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.skattetabell.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.skattetabell(class="form-control form-control-lg") }}
                            {% endif %}  
                        </div>
                        <div class="form-group">
                            {{ form.expat_type.label(class="form-control-label") }}
                            {% if form.expat_type.errors %}
                                {{ form.expat_type(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.expat_type.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.expat_type(class="form-control form-control-lg") }}
                            {% endif %}  
                        </div>
                        <div class="form-group">
                            {{ form.assign_start.label(class="form-control-label") }}
                            {% if form.assign_start.errors %}
                                {{ form.assign_start(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.assign_start.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.assign_start(class="form-control form-control-lg", placeholder="YYYY-MM-DD") }}
                            {% endif %}  
                        </div>
                        <div class="form-group">
                            {{ form.assign_end.label(class="form-control-label") }}
                            {% if form.assign_end.errors %}
                                {{ form.assign_end(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.assign_end.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.assign_end(class="form-control form-control-lg", placeholder="YYYY-MM-DD") }}
                            {% endif %}  
                        </div>
                        <div class="form-check">
                            {{ form.expert(class="form-check-input") }}
                            {{ form.expert.label(class="form-check-label") }}
                        </div>
                        <div class="form-check">
                            {{ form.sink(class="form-check-input") }}
                            {{ form.sink.label(class="form-check-label") }}
                        </div>
                        <div class="form-check">
                            {{ form.six_month_rule(class="form-check-input") }}
                            {{ form.six_month_rule.label(class="form-check-label") }}
                        </div>
                        <div class="form-group">
                            {{ form.social_security.label(class="form-control-label") }}
                            {% if form.social_security.errors %}
                                {{ form.social_security(class="form-control form-control-lg is-invalid") }}    
                                <div class="invalid-feedback">
                                    {% for error in form.social_security.errors %}
                                        <span>{{ error }} </span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.social_security(class="form-control form-control-lg") }}
                            {% endif %}  
                        </div>
                    </fieldset>
                    <div class="modal-footer">
                    
                        <div class="form-group">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            {{ form.submit(class="btn btn-primary", id="uform")}}
                        </div>
                    </div>
                </form>
            </div>


<script>
    $('#uform').click(function(event) {
        event.preventDefault();
        var url = "{{ url_for('main.employeeForm') }}"
        $.post(url, data=$('#editForm').serialize(), function(data) {
            if (data.status == 'ok') {
                $('#myModal').modal('hide');
                location.reload();
            }
            else {
                $('#myModal .modal-content').html(data);
            }
        });
    })
</script>

app/templates/modalForms/deletePayItem.html
<div class="modal-header">
    <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-danger" value="Delete" onclick="deletePayItem('{{ url_for('main.delete_pay_item', pay_id=pay_id) }}', {{pay_id}})">Delete</button>
</div>

app/templates/modalForms/deletePayRun.html
<div class="modal-header">
    <h5 class="modal-title" id="deleteModalLabel">Delete Payrun?</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
    <button type="button" class="btn btn-danger" value="Delete"
        onclick="deletePayRun('{{ url_for('main.delete_pay_run', pay_run_id = pay_run_id) }}', {{pay_run_id}})">Delete</button>
</div>

app/templates/modalForms/payRunForm.html
<div class="modal-header">
    <h5 class="modal-title" id="staticBackdropLabel">Add Pay Item!</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
        <div class="form-group">
            <form action="{{ url_for('main.create_payroll_run') }}" method="post" id="editForm">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.year.label(class="form-control-label") }}
                        {% if form.year.errors %}
                            {{ form.year(class="form-control form-control-lg is-invalid") }}    
                            <div class="invalid-feedback">
                                {% for error in form.year.errors %}
                                    <span>{{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.year(class="form-control form-control-lg") }}
                        {% endif %}  
                    </div>
                    <div class="form-group">
                        {{ form.month.label(class="form-control-label") }}
                        {% if form.month.errors %}
                            {{ form.month(class="form-control form-control-lg is-invalid") }}    
                            <div class="invalid-feedback">
                                {% for error in form.month.errors %}
                                    <span>{{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.month(class="form-control form-control-lg") }}
                        {% endif %}  
                    </div>
                </fieldset>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{ form.submit(class="btn btn-primary", id="uform")}}
                    </div>
                </div>
            </form>
        </div>


<script>
$('#uform').click(function(event) {
    event.preventDefault();
    var url = "{{ url_for('main.create_payroll_run') }}"
    $.post(url, data=$('#editForm').serialize(), function(data) {
        if (data.status == 'ok') {
        $('#myModal').modal('hide');
        location.reload();
        }
        else {
        $('#myModal .modal-content').html(data);
        }
    });
})
</script>

app/templates/modalForms/payitemform.html
<div class="modal-header">
    <h5 class="modal-title" id="staticBackdropLabel">Add Pay Item!</h5>
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
        <div class="form-group">
            <form action="{{ url_for('main.pay_item') }}" method="post" id="editForm">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.pay_item.label(class="form-control-label") }}
                        {% if form.pay_item.errors %}
                            {{ form.pay_item(class="form-control form-control-lg is-invalid") }}    
                            <div class="invalid-feedback">
                                {% for error in form.pay_item.errors %}
                                    <span>{{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.pay_item(class="form-control form-control-lg") }}
                        {% endif %}                      
                    </div>
                    <div class="form-group">
                        {{ form.tax_setting.label(class="form-control-label") }}
                        {% if form.tax_setting.errors %}
                            {{ form.tax_setting(class="form-control form-control-lg is-invalid") }}    
                            <div class="invalid-feedback">
                                {% for error in form.tax_setting.errors %}
                                    <span>{{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.tax_setting(class="form-control form-control-lg") }}
                        {% endif %}  
                    </div>
                    <div class="form-group">
                        {{ form.cash_type.label(class="form-control-label") }}
                        {% if form.cash_type.errors %}
                            {{ form.cash_type(class="form-control form-control-lg is-invalid") }}    
                            <div class="invalid-feedback">
                                {% for error in form.cash_type.errors %}
                                    <span>{{ error }} </span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.cash_type(class="form-control form-control-lg") }}
                        {% endif %}  
                    </div>
                </fieldset>
                <div class="modal-footer">
                    <div class="form-group">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {{ form.submit(class="btn btn-primary", id="uform")}}
                    </div>
                </div>
            </form>
        </div>


<script>
$('#uform').click(function(event) {
    event.preventDefault();
    var url = "{{ url_for('main.pay_item') }}"
    $.post(url, data=$('#editForm').serialize(), function(data) {
        if (data.status == 'ok') {
        $('#myModal').modal('hide');
        location.reload();
        }
        else {
        $('#myModal .modal-content').html(data);
        }
    });
})
</script>