app/main/routes.py
from flask import flash, redirect, session, url_for, render_template, request, Blueprint, jsonify
from app.users.routes import current_user

from app import db
from app.helpers import login_required
from app.models import Company, Employee, PayItem, EmployeePayItem, User, MonthlyPayItem, PayRun, MonthlyEmployee, MonthResult
from app.calculations.forms import (AddCompany, AddEmployee, CalculateInitial, EditEmployee, 
                        EditCompany, PayItems, AddEmployeePayItems, AuthorizationForm, PayRunForm)
from app.calculations.funktioner import Expat


main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
@login_required
def home():

    user = User.query.filter_by(id=current_user.get_id()).first()
    
    return render_template("company/home.html",company = user.access)

@main.route("/home/<int:company_id>")
def chosen_company(company_id):

    company = Company.query.get_or_404(company_id)
    session['current_company'] = company.company_name

    return redirect(url_for('main.employee'))

@main.route("/employee", methods=["GET", "POST"])
@login_required
def employee():

    page = request.args.get('page', 1, type=int)
    form = AddEmployee()

    try:
        get_company = Company.query.filter_by(company_name = session['current_company']).first()
        all_employees = Employee.query.filter_by(company_id = get_company.id).paginate(page = page, per_page = 5)
    except:
        flash('You need to pick a company first!', 'danger')
        return redirect(url_for('main.home'))

    return render_template("employees/employee_grid.html",employees = all_employees, company = get_company, form = form)

@main.route("/employeeForm", methods=["GET", "POST"])
@login_required
def employeeForm():

    form = AddEmployee()
    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        emp_to_add = Employee(first_name = form.first_name.data, last_name = form.last_name.data, person_nummer = form.person_nummer.data,
                             skattetabell = form.skattetabell.data, expat_type = form.expat_type.data, assign_start = form.assign_start.data,
                             assign_end = form.assign_end.data, expert = form.expert.data, sink = form.sink.data, six_month_rule = form.six_month_rule.data,
                             social_security = form.social_security.data, company_id = current_company) 

        db.session.add(emp_to_add)
        db.session.commit()

        flash('the employee has been added! You can now start calculating', 'success')
        return jsonify(status="ok")
    return render_template("modalForms/addEmployeeForm.html", form = form)

@main.route("/editEmployeeForm/<int:employee_id>", methods=["GET", "POST"])
@login_required
def editEmployeeForm(employee_id):
    employee = Employee.query.get_or_404(employee_id)
    session["current_employee"] = employee_id
    emp_pay_items = employee.pay_items

    form = EditEmployee(obj=employee)
    pay_form = AddEmployeePayItems()

    current_company = Company.query.filter_by(company_name = session['current_company']).first()
    company_pay_items = current_company.pay_items
    

    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        try:
            employee = Employee.query.get_or_404(employee_id)
        except:
            flash('Employee not found!', 'danger')
            return redirect(url_for('main.home'))

        form.populate_obj(employee)

        db.session.commit()

        flash('the employee has been updated! You can now start calculating', 'success')
        return jsonify(status="ok")

    return render_template("modalForms/editEmployee.html", form = form, employee = employee, company_pay_items = company_pay_items, emp_pay_items = emp_pay_items, pay_form = pay_form)



@main.route("/employee/<int:employee_id>")
def chosen_employee(employee_id):
    employee = Employee.query.get_or_404(employee_id)

    get_employee = Employee.query.filter_by(id = employee.id).first()
    session['employee'] = get_employee.id

    return redirect(url_for('main.calculate'))

@main.route("/add_company", methods=["GET", "POST"])
@login_required
def add_company():

    form = AddCompany()
    session["current_company"] = ""

    if form.validate_on_submit():
        comp_to_add = Company(company_name = form.company_name.data, org_number = form.org_number.data,
                             permanent_establishment = form.permanent_establishment.data) 

        db.session.add(comp_to_add)
        db.session.commit()

        added_company = Company.query.filter_by(company_name = form.company_name.data).first()
        user = User.query.filter_by(id=current_user.get_id()).first()

        user.access.append(added_company)
        db.session.commit()

        session['current_company'] = form.company_name.data

        flash('the company has been created! You can now add employees', 'success')
        return redirect(url_for('main.settings'))

    return render_template("company/company_settings.html", form=form, current_company = False, title='Company', pay_items = False)



@main.route("/settings", methods=["GET", "POST"])
@login_required
def settings():

    try:
        current_company = Company.query.filter_by(company_name = session['current_company']).first()
        edit_form = EditCompany(obj=current_company)
    except:
        edit_form = EditCompany()

    try:
        page = request.args.get('page', 1, type=int)
        pay_items = PayItem.query.filter_by(company_id = current_company.id).paginate(page = page, per_page = 5)
    except:
        pay_items = False

    authorization_form = AuthorizationForm()
    authorized_users = current_company.users

    if edit_form.validate_on_submit():
        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first()
        except:
            flash('Some error with chosen company', 'danger')

        edit_form.populate_obj(current_company)
        db.session.commit()
        session['current_company'] = edit_form.company_name.data

        flash('the company has been edited!', 'success')
        return redirect(url_for('main.settings'))

    return render_template("company/company_settings.html", current_company = current_company, form = edit_form,
             pay_items = pay_items, authorization_form = authorization_form, authorized_users = authorized_users)


@main.route("/company_start", methods=["GET", "POST"])
@login_required
def company_start():

    form = PayRunForm()

    try:
        current_company = Company.query.filter_by(company_name = session['current_company']).first()
        pay_runs = current_company.payroll_runs
    except:
        flash('You need to pick a company first!', 'danger')
        return redirect(url_for('main.home'))

    return render_template("company/company_start.html", current_company = current_company, pay_runs = pay_runs, form = form)


@main.route("/pay_item", methods=["GET", "POST"])
@login_required
def pay_item():

    form = PayItems()
    if form.validate_on_submit():

        try:
            current_company = Company.query.filter_by(company_name = session['current_company']).first().id
        except:
            flash('You need to pick a company first!', 'danger')
            return redirect(url_for('main.home'))

        pay_item = PayItem(pay_item = form.pay_item.data, tax_setting = form.tax_setting.data, cash_type = form.cash_type.data, company_id = current_company) 
        db.session.add(pay_item)
        db.session.commit()

        flash('the pay item has been added! You can now start calculating', 'success')
        return jsonify(status="ok")
    return render_template("modalForms/payItemForm.html", form = form)


@main.route("/pay_item/<int:pay_id>/delete", methods=["GET", "POST"])
@login_required
def delete_pay_item(pay_id):

    if request.method == 'POST':
        chosen_item = PayItem.query.get_or_404(pay_id)
        db.session.delete(chosen_item)
        db.session.commit()

        return jsonify(status="ok")
    else:
        return render_template("modalForms/deletePayItem.html",pay_id = pay_id)

@main.route("/emp_pay_item/<int:employee_id>", methods=["GET", "POST"])
@login_required
def emp_pay_item(employee_id):

    employee = Employee.query.get_or_404(employee_id)
    form = EditEmployee(obj=employee)

    current_company = Company.query.filter_by(company_name = session['current_company']).first()
    company_pay_items = current_company.pay_items
    emp_pay_items = employee.pay_items
    pay_form = AddEmployeePayItems()

    if pay_form.validate_on_submit():

        chosen_item = request.form.get('payitemss')
        amount = request.form.get('amount')
        currency = request.form.get('currency')


        to_add = EmployeePayItem(pay_item_id=chosen_item, amount = amount, currency = currency, employee_id = employee_id)
        db.session.add(to_add)
        db.session.commit()

        item_to_return = EmployeePayItem.query.filter_by(pay_item_id = chosen_item, amount = amount).first()
        company_pay_item = PayItem.query.filter_by(id=item_to_return.pay_item_id).first()
        return jsonify(status="ok", pay_item_id=item_to_return.id, pay_item = company_pay_item.pay_item, tax_setting = company_pay_item.tax_setting, cash_type = company_pay_item.cash_type, amount = amount, currency = currency, employee_id = employee_id)

app/templates/company/add_company.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}

{% block main %}

    <div class="form-group">
        <form action="/add_company" method="post">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Add Company! </legend>
                <div class="form-group">
                    {{ form.company_name.label(class="form-control-label") }}

                    {% if form.company_name.errors %}
                        {{ form.company_name(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.company_name.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.company_name(class="form-control form-control-lg") }}
                    {% endif %}                      
                </div>
                <div class="form-group">
                    {{ form.org_number.label(class="form-control-label") }}
                    {% if form.org_number.errors %}
                        {{ form.org_number(class="form-control form-control-lg is-invalid") }}    
                        <div class="invalid-feedback">
                            {% for error in form.org_number.errors %}
                                <span>{{ error }} </span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.org_number(class="form-control form-control-lg") }}
                    {% endif %}  
                </div>
                <div class="form-check">
                    {{ form.permanent_establishment(class="form-check-input") }}
                    {{ form.permanent_establishment.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info")}}
            </div>
        </form>
    </div>

<div class="border-top pt-3">
    <small class="text-muted">
        Want to choose a company? <a class="ml-2" href="{{ url_for('main.home') }}">Pick now</a>
    </small>
</div>

{% endblock %}

app/templates/company/company1.html
{% extends "layout.html" %}

{% block title %}
    Apology
{% endblock %}



{% block main %}
    <div id="block">
        <h1> Select a company </h1>
            <form action="/company" method="post">
                <div class="form-group">
                    <select class= "form-group" name="company">
                        <option disabled selected value>Company</option>
                        {% for item in rows%}
                        <option value= "{{ item.company_name }}">{{ item.company_name }}</option>
                        {%endfor%}
                    </select>
                </div>
                <button class="btn btn-primary" type="submit">Pick Company</button>
            </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Want to add a company? <a class="ml-2" href="{{ url_for('main.add_company') }}">Add Company</a>
        </small>
    </div>
{% endblock %}

app/templates/company/company_settings.html
{% extends "layout_no_container.html" %}

{% block title %}
    Log In
{% endblock %}

{% block main %}
<ul class= "nav" id="second_navbar">
    {% if current_company %}
        <h4 class="nav_heading"><a id="nav-start" href="{{ url_for('main.company_start') }}">Start</a></h4>
        <h4 class="nav_heading active-nav"><a id="nav-settings">Settings</a></h4>
        <h4 class="nav_heading"><a id="nav-employees" href="{{ url_for('main.employee') }}">Employees</a></h4>
    {% else %}
        <h4 class="nav_heading disabled-nav"><a >Start</a></h4>
        <h4 class="nav_heading active-nav"><a>Settings</a></h4>
        <h4 class="nav_heading disabled-nav"><a>Employees</a></h4>
    {% endif %}
</ul>
<div class="container p-5 own-cont">
    <nav>
        <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">General Settings</a>
            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Team Access</a>
            <a class="nav-item nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Pay Items</a>
        </div>
    </nav>
        <div class="tab-content" id="nav-tabContent">
            <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                    <div class="form-group">
                            {% if current_company %}
                                <form action="/settings" method="post">
                            {% else %}
                                <form action="/add_company" method="post">
                            {% endif %}
                                {{ form.hidden_tag() }}
                                <fieldset class="form-group">
                                    {% if current_company %}
                                        <legend class="border-bottom mb-4"> Edit Company! </legend>
                                    {% else %}
                                        <legend class="border-bottom mb-4"> Add Company! </legend>
                                    {% endif %}

                                    <div class="form-group">
                                        {{ form.company_name.label(class="form-control-label") }}
                    
                                        {% if form.company_name.errors %}
                                            {{ form.company_name(class="form-control form-control-lg is-invalid") }}    
                                            <div class="invalid-feedback">
                                                {% for error in form.company_name.errors %}
                                                    <span>{{ error }} </span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.company_name(class="form-control form-control-lg") }}
                                        {% endif %}                      
                                    </div>
                                    <div class="form-group">
                                        {{ form.org_number.label(class="form-control-label") }}
                                        {% if form.org_number.errors %}
                                            {{ form.org_number(class="form-control form-control-lg is-invalid") }}    
                                            <div class="invalid-feedback">
                                                {% for error in form.org_number.errors %}
                                                    <span>{{ error }} </span>
                                                {% endfor %}
                                            </div>
                                        {% else %}
                                            {{ form.org_number(class="form-control form-control-lg") }}
                                        {% endif %}  
                                    </div>
                                    <div class="form-check">
                                        {{ form.permanent_establishment(class="form-check-input") }}
                                        {{ form.permanent_establishment.label(class="form-check-label") }}
                                    </div>
                                </fieldset>
                                <div class="modal-footer">
                                    <div class="form-group">
                                        {{ form.submit(class="btn btn-primary")}}
                                    </div>
                                </div>
                            </form>
                    </div>
            </div>

            <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
                <legend class="border-bottom mb-4"> Manage access! </legend>
                {%if authorized_users %}
                    <table class="table table-striped table-dark">
                        <thead>
                            <tr>
                                <th scope="col">Username</th>
                                <th scope="col">Email</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in authorized_users %}
                                <tr class="payItemRow" id="{{item.id}}"> 
                                    <td>{{ item.username }}</td>
                                    <td>{{ item.email }}</td>                                    
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                {% endif %}

                {% if authorization_form %}
                <div class="form-group">
                    <form action="{{ url_for('main.add_user_access')}}" method="post">

                        {{ authorization_form.hidden_tag() }}
                        <fieldset class="form-group">                        

                            <div class="form-group">
                                {{ authorization_form.email.label(class="form-control-label") }}
            
                                {% if authorization_form.email.errors %}
                                    {{ authorization_form.email(class="form-control form-control-lg is-invalid") }}    
                                    <div class="invalid-feedback">
                                        {% for error in authorization_form.email.errors %}
                                            <span>{{ error }} </span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{ authorization_form.email(class="form-control form-control-lg") }}
                                {% endif %}                      
                            </div>
                        </fieldset>
                        <div class="modal-footer">
                            <div class="form-group">
                                {{ authorization_form.submit(class="btn btn-primary")}}
                            </div>
                        </div>
                    </form>
                </div>
                {% else %}
                {% endif%}
            </div>

            {% if current_company %}
                <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
                    <div class="left-align-button">
                            <button type="button" class="btn btn-primary" onclick="payItem('{{ url_for('main.pay_item') }}')">Add Pay Item</button>
                    </div>
                    <table class="table table-striped table-dark">
                        <thead>
                            <tr>
                                <th scope="col">Pay Item</th>
                                <th scope="col">Tax Setting</th>
                                <th scope="col">Cash Type</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% if pay_items %}
                                {% for item in pay_items.items %}
                                    <tr class="payItemRow" id="{{item.id}}"> 
                                        <td>{{ item.pay_item }}</td>
                                        <td>{{ item.tax_setting }}</td>
                                        <td>{{ item.cash_type }}</td>
                                        <td><button type="button" class="btn btn-danger btn-sm m-1" onclick="delPayItem('{{ url_for('main.delete_pay_item',pay_id = item.id) }}')">Delete</button></td>
                                    </tr>
                                {% endfor %}
                            {% else %}

                            {% endif %}
                        </tbody>
                    </table>

                    {% if pay_items %}
                        {% for page_num in pay_items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                            {% if page_num %}
                                    {% if pay_items.page == page_num %}
                                        <a class="btn btn-info mb-4" href= "{{ url_for('main.settings', page=page_num) }}">{{ page_num }}</a>
                                    {% else %}
                                        <a class="btn btn-outline-info mb-4" href= "{{ url_for('main.settings', page=page_num) }}">{{ page_num }}</a>
                                    {% endif %}        
                            {% else %}
                            
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        
                    {% endif %}
                
                {% else %}
                <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-profile-tab">...</div>
                {% endif %}    

                <div class="modal fade bd-example-modal-xl" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" id="myModal">
                    <div class="modal-dialog modal-xl" role="document">
                        <div class="modal-content">
            
                        </div>
                    </div>
                </div>
                <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">


                        </div>
                    </div>
                </div>
            </div>
        </div>

</div>

<script>



function payItem(url){
        $.get(url, function(data) {
        $('#myModal .modal-content').html(data);
        $('#myModal').modal();
        });
    }

function delPayItem(url){
        $.get(url, function(data) {
        $('#deleteModal .modal-content').html(data);
        $('#deleteModal').modal();
        });
    }
        

function deletePayItem(url, pay_id){
    $.post(url, function(data) {
        if (data.status == 'ok') {
        $('#deleteModal').modal('hide');
        animateDel(pay_id);
        }
        else {
        $('#deleteModal .modal-content').html(data);
        }
    });
}

function animateDel(pay_id){
    var element = document.getElementById(pay_id)
    element.style.animationPlayState = 'running';
    element.addEventListener('animationend', () =>  {
                  element.remove();
              });
}
    
</script>

{% endblock %}

app/templates/company/company_start.html
{% extends "layout_no_container.html" %}

{% block title %}
Log In
{% endblock %}

{% block main %}
<ul class="nav" id="second_navbar">
    {% if current_company %}
    <h4 class="nav_heading active-nav"><a id="nav-start">Start</a></h4>
    <h4 class="nav_heading"><a id="nav-settings" href="{{ url_for('main.settings') }}">Settings</a></h4>
    <h4 class="nav_heading"><a id="nav-employees" href="{{ url_for('main.employee') }}">Employees</a></h4>
    {% else %}
    <h4 class="nav_heading active-nav"><a>Start</a></h4>
    <h4 class="nav_heading disabled-nav"><a>Settings</a></h4>
    <h4 class="nav_heading disabled-nav"><a>Employees</a></h4>
    {% endif %}
</ul>
<div class="container p-5">
    <div class="titlebar-container">
        <div class="titlebar">
            <h1 class="title">{{ current_company.company_name }}</h1>
        </div>
    </div>
    <div class="left-align-button">
        <button type="button" class="btn btn-primary" onclick="payRun('{{ url_for('main.create_payroll_run') }}')">Add
            Month</button>
    </div>

    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">Month</th>
                <th scope="col">Year</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in pay_runs %}
            <tr class="payItemRow" id="{{item.id}}">
                <td>{{ item.month }}</td>
                <td>{{ item.year }}</td>
                <form action="{{ url_for('main.calculate_payroll_run', pay_run_id=item.id) }}">
                    <td>
                        <button type="submit" class="btn btn-primary">Edit Month</button>
                        <button type="button" class="btn btn-danger btn-sm m-1"
                            onclick="delPayRun('{{ url_for('main.delete_pay_run',pay_run_id = item.id) }}')">Delete</button>
                    </td>
                </form>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <div class="modal fade bd-example-modal-xl" data-backdrop="static" tabindex="-1" role="dialog"
        aria-labelledby="myExtraLargeModalLabel" aria-hidden="true" id="myModal">
        <div class="modal-dialog modal-xl" role="document">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">


            </div>
        </div>
    </div>
</div>

<script>

    function payRun(url) {
        $.get(url, function (data) {
            $('#myModal .modal-content').html(data);
            $('#myModal').modal();
        });
    }

    function delPayRun(url) {
        $.get(url, function (data) {
            $('#deleteModal .modal-content').html(data);
            $('#deleteModal').modal();
        });
    }

    function deletePayRun(url, pay_id) {
        $.post(url, function (data) {
            if (data.status == 'ok') {
                $('#deleteModal').modal('hide');
                animateDel(pay_id);
            }
            else {
                $('#deleteModal .modal-content').html(data);
            }
        });
    }

    function animateDel(pay_id) {
        var element = document.getElementById(pay_id)
        element.style.animationPlayState = 'running';
        element.addEventListener('animationend', () => {
            element.remove();
        });
    }

</script>


{% endblock %}

app/templates/company/home.html
{% extends "layout.html" %}

{% block title %}
    Log In
{% endblock %}

{% block main %}

    <div class="titlebar-container">
        <div class="titlebar">
            <h1 class="title">List of Companies</h1>
        </div>
    </div>
    <div class="left-align-button">
        <form action="{{ url_for('main.add_company') }}">
            <button type="submit" class="btn btn-primary">Add Company</button>
        </form>
    </div>
    <table class="table table-striped table-dark">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Company Name</th>
                <th scope="col">Organization number</th>
                <th scope="col">Permanent Establishment</th>
            </tr>
        </thead>
        <tbody>
            {% for item in company %}
                <tr data-href="{{ url_for('main.chosen_company', company_id=item.id) }}"> 
                    <th scope="row">{{ item.id }}</th>
                    <td>{{ item.company_name }}</td>
                    <td>{{ item.org_number }}</td>
                    <td>{{ item.permanent_establishment }}</td>
                    <form action="{{ url_for('main.chosen_company', company_id=item.id) }}">
                        <td><button type="submit" class="btn btn-primary" >Edit Company</button></td>
                    </form>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}